s=set()
n=int(input("Enter the number 1:"))
s.add(n)
n=int(input("Enter the number 2:"))
s.add(n)
n=int(input("Enter the number 3:"))
s.add(n)
n=int(input("Enter the number 4:"))
s.add(n)
n=int(input("Enter the number 5:"))
s.add(n)
n=int(input("Enter the number 6:" ))
s.add(n)
n=int(input("Enter the number 7:"))
s.add(n)
n=int(input("Enter the number 8:"))
s.add(n)
print(s)